title: Sigma Specification
description: All the specifications of Sigma
show_downloads: false
color-scheme: auto
logo: /images/Sigma_0.3.png
favicon: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

remote_theme: BDHU/minimalist

sidebar:
  - name: Index
    icon: <i class="fa-solid fa-pen-nib"></i>
    link: /sigma-specification/index.html
  - name: Sigma Rules
    icon: <i class="fa-solid fa-pen-nib"></i>
    link: /sigma-specification/Sigma_specification.html
  - name: Tags
    icon: <i class="fa-solid fa-pen-nib"></i>
    link: /sigma-specification/Tags_specification.html
  - name: Taxonomy
    icon: <i class="fa-solid fa-pen-nib"></i>
    link: /sigma-specification/Taxonomy_specification.html
  - name: SigmaHQ Filename Normalisation
    icon: <i class="fa-solid fa-pen-nib"></i>
    link: /sigma-specification/sigmahq/Sigmahq_filename_rule.html
  - name: SigmaHQ Rules
    icon: <i class="fa-solid fa-file-shield"></i>
    link: https://github.com/SigmaHQ/sigma
  - name: PySigma Converter
    icon: <i class="fa-solid fa-screwdriver-wrench"></i>
    link: https://github.com/SigmaHQ/pySigma
 