title: Sigma Blueprint
description: All the specifications of Sigma format
show_downloads: false
color-scheme: auto
logo: /images/Sigma_0.3.png
favicon: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

remote_theme: BDHU/minimalist

sidebar:
  - name: Home
    icon: <i class="fa-solid fa-house"></i>
    link: /sigma-specification/index.html
  - name: Rules
    icon: <i class="fa-solid fa-pen-nib"></i>
    link: /sigma-specification/Sigma_specification.html
  - name: Tags
    icon: <i class="fa-solid fa-pen-nib"></i>
    link: /sigma-specification/Tags_specification.html
  - name: Taxonomy
    icon: <i class="fa-solid fa-pen-nib"></i>
    link: /sigma-specification/Taxonomy_specification.html
  - name: SigmaHQ Filename Normalisation
    icon: <i class="fa-solid fa-pen-nib"></i>
    link: /sigma-specification/sigmahq/Sigmahq_filename_rule.html
  - name: Github repository
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/SigmaHQ/sigma-specification
  - name: SigmaHQ Rules
    icon: <i class="fa-solid fa-file-shield"></i>
    link: https://github.com/SigmaHQ/sigma
  - name: PySigma Converter
    icon: <i class="fa-solid fa-screwdriver-wrench"></i>
    link: https://github.com/SigmaHQ/pySigma
 
# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error â€”
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]