title: Sigma Specification
description: All the specifications of Sigma
show_downloads: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

remote_theme: BDHU/minimalist

sidebar:
  - name: Index
    link: ./index.html
  - name: Sigma Rules
    link: ./Sigma_specification.html
  - name: Tags
    link: ./Tags_specification.html
  - name: Taxonomy
    link: ./Taxonomy_specification.html
  - name: SigmaHQ Filename Normalisation
    link: ./sigmahq/Sigmahq_filename_rule.html